on:
  push:
    branches:
      - master
      - 'test-*'
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7' ]
    name: Vagrant Share unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          architecture: 'x64'
      - name: Run Tests
        run: .ci/test.sh
